server:
  port: 7799


myResourceRoot: D:/liaoyj/DevelopmentResources

myResourceRoot2: D:/liaoyj/DevelopmentDoc

imagesNumOfOpenViewer: 5

spring:
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, file:${myResourceRoot}
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
